<Project >
    <PropertyGroup>
        <NoWarn>CA1416</NoWarn>
        <TargetFramework>net10.0-windows</TargetFramework>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <SatelliteResourceLanguages>None</SatelliteResourceLanguages>
        <PlatformTarget>x64</PlatformTarget>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <LangVersion>latest</LangVersion>
        <GenerateSatelliteAssembliesForCore>false</GenerateSatelliteAssembliesForCore>
        <Optimize>true</Optimize>
        <DebugType>none</DebugType>
        <DebugSymbols>false</DebugSymbols>
    </PropertyGroup>
    <PropertyGroup>
        <DalamudLibPath>$(appdata)\XIVLauncherCN\addon\Hooks\dev\</DalamudLibPath>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>
</Project>
