<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SilverDasher.Core</AssemblyName>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <RootNamespace>SilverDasher</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MQTTnet" Version="5.1.0.1559"/>
    <Reference Include="FFXIV_ACT_Plugin.Common">
      <HintPath>..\..\external_dependencies\SDK\FFXIV_ACT_Plugin.Common.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Lumina">
      <HintPath>$(DalamudLibPath)Lumina.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Lumina.Excel">
      <HintPath>$(DalamudLibPath)Lumina.Excel.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(DalamudLibPath)Newtonsoft.Json.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Content Include="SilverDasher.Weaver.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Reference Include="Dalamud">
      <HintPath>$(DalamudLibPath)Dalamud.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Dalamud.Bindings.ImGui">
      <HintPath>$(DalamudLibPath)Dalamud.Bindings.ImGui.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <ProjectReference Include="..\..\machina\Machina.FFXIV\Machina.FFXIV.csproj"/>
    <ProjectReference Include="..\..\NotACT\NotACT.csproj"/>
  </ItemGroup>
</Project>