<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SilverDasher.Core</AssemblyName>
    <UseWindowsForms>True</UseWindowsForms>
    <PlatformTarget>x64</PlatformTarget>
    <UseWpf>true</UseWpf>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <RootNamespace>SilverDasher</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Toolkit.Uwp.Notifications" Version="7.1.3"/>
    <PackageReference Include="MQTTnet" Version="4.3.7.1207"/>
    <Reference Include="FFXIV_ACT_Plugin.Common">
      <HintPath>..\..\external_dependencies\SDK\FFXIV_ACT_Plugin.Common.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Lumina">
      <HintPath>$(DalamudLibPath)Lumina.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Lumina.Excel">
      <HintPath>$(DalamudLibPath)Lumina.Excel.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(DalamudLibPath)Newtonsoft.Json.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Content Include="SilverDasher.Weaver.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Reference Include="Dalamud">
      <HintPath>$(DalamudLibPath)Dalamud.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <ProjectReference Include="..\..\NotACT\NotACT.csproj"/>
    <ProjectReference Include="..\Zodiark\Zodiark.csproj"/>
  </ItemGroup>
</Project>