<Project Sdk="Dalamud.NET.Sdk/14.0.2">
  <PropertyGroup>
    <Author>Usagi, Latihas</Author>
    <Company>Dezent</Company>
    <Version>2.10.1.0</Version>
    <Description>A parsing plugin.</Description>
    <AssemblyName>IINACTEx</AssemblyName>
    <OutputPath>bin/</OutputPath>
    <Copyright></Copyright>
    <Description>该插件会在一个类ACT的环境下运行FFXIV_ACT_Plugin与大量修改的Overlay Plugin以适配现代.NET。与此同时，也添加了大量修改的Triggernometry与Postnamazu。包括类ACT、Triggernometry、Postnamazu在内，这些并非完整的代码移植，并且仍在开发完善中，可能缺少部分原版的函数，开发时请注意。</Description>
    <PunchLine>我用ACT，我是绿玩。(如果加载失败，再加载一次即可。如果你是从上古版本更新而来，有文件占用bug，请先禁用旧版插件，然后!!!重启游戏!!!，然后删除旧版插件，再安装新版插件)</PunchLine>
    <PackageProjectUrl>https://github.com/Latihas/IINACTEx</PackageProjectUrl>
    <Name>IINACTEx</Name>
    <IconUrl>https://raw.githubusercontent.com/marzent/IINACT/master/images/icon.png</IconUrl>
    <RepoUrl>https://github.com/Latihas/IINACTEx</RepoUrl>
    <Tags>parsing;plugin;ACT</Tags>
    <AssemblyVersion>7.45.2.6</AssemblyVersion>
  </PropertyGroup>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWpf>true</UseWpf>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.CsWin32" Version="*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NAudio" Version="*"/>
    <PackageReference Include="System.Speech" Version="*"/>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../EdgeTTS/EdgeTTS.csproj"/>
    <ProjectReference Include="../FetchDependencies/FetchDependencies.csproj"/>
    <ProjectReference Include="../machina/Machina.FFXIV/Machina.FFXIV.csproj"/>
    <ProjectReference Include="../machina/Machina/Machina.csproj"/>
    <ProjectReference Include="../NotACT/NotACT.csproj"/>
    <ProjectReference Include="../OverlayPlugin.Core/OverlayPlugin.Core.csproj"/>
    <ProjectReference Include="../Triggernometry/Source/Triggernometry/TriggernometryPlugin.csproj"/>
    <ProjectReference Include="../PostNamazu/PostNamazu/PostNamazu.csproj"/>
    <ProjectReference Include="../SilverDasher/SilverDasher/SilverDasher.csproj"/>
    <ProjectReference Include="../Unscrambler/Unscrambler/Unscrambler.csproj"/>
    <!--    <PackageReference Include="Unscrambler.XIV.CN" Version="*" />-->
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="../EdgeTTS/voices.json">
      <Link>Resources/voices.json</Link>
      <LogicalName>IINACT.Resources.voices.json</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="FFXIV_ACT_Plugin">
      <HintPath>../external_dependencies/FFXIV_ACT_Plugin.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="FFXIV_ACT_Plugin.Common">
      <HintPath>../external_dependencies/SDK/FFXIV_ACT_Plugin.Common.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="FFXIV_ACT_Plugin.Config">
      <HintPath>../external_dependencies/SDK/FFXIV_ACT_Plugin.Config.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="FFXIV_ACT_Plugin.Logfile">
      <HintPath>../external_dependencies/SDK/FFXIV_ACT_Plugin.Logfile.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="FFXIV_ACT_Plugin.Memory">
      <HintPath>../external_dependencies/SDK/FFXIV_ACT_Plugin.Memory.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="FFXIV_ACT_Plugin.Network">
      <HintPath>../external_dependencies/SDK/FFXIV_ACT_Plugin.Network.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="FFXIV_ACT_Plugin.Parse">
      <HintPath>../external_dependencies/SDK/FFXIV_ACT_Plugin.Parse.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="FFXIV_ACT_Plugin.Resource">
      <HintPath>../external_dependencies/SDK/FFXIV_ACT_Plugin.Resource.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Content Include="../external_dependencies/SafeMemoryReader.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Res/**/*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>$([System.String]::Copy('%(RecursiveDir)').Replace('Res/', ''))%(Filename)%(Extension)</TargetPath>
    </Content>
    <EmbeddedResource Include="logo.png"/>
  </ItemGroup>
  <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == ''">
    <DalamudLibPath>$(appdata)/XIVLauncherCN/addon/Hooks/dev</DalamudLibPath>
    <AssemblySearchPaths>$(AssemblySearchPaths);$(DalamudLibPath)</AssemblySearchPaths>
  </PropertyGroup>
</Project>
