<Project Sdk="Dalamud.NET.Sdk/15.0.0">
	<PropertyGroup>
		<Author>Usagi, Latihas</Author>
		<Company>Dezent</Company>
		<Version>2.10.3.1</Version>
		<Description>该插件会在一个类ACT的环境下运行FFXIV_ACT_Plugin与大量修改的Overlay Plugin以适配现代.NET。与此同时，也添加了大量修改的Triggernometry与Postnamazu。包括类ACT、Triggernometry、Postnamazu在内，这些并非完整的代码移植，并且仍在开发完善中，可能缺少部分原版的函数，开发时请注意。</Description>
		<Copyright></Copyright>
		<PackageProjectUrl>https://github.com/Latihas/IINACTEx</PackageProjectUrl>
		<AssemblyName>IINACTEx</AssemblyName>
		<OutputPath>../bin</OutputPath>
		<UseWindowsForms>true</UseWindowsForms>
		<PunchLine>我用ACT，我是绿玩。(如果加载失败，请尝试重启游戏。如果还是不行，清除IINACTEx相关文件与数据再安装)</PunchLine>
		<Name>IINACTEx</Name>
		<IconUrl>https://raw.githubusercontent.com/marzent/IINACT/master/images/icon.png</IconUrl>
		<RepoUrl>https://github.com/Latihas/IINACTEx</RepoUrl>
		<Tags>parsing;plugin;ACT</Tags>
		<AssemblyVersion>7.51.1.2</AssemblyVersion>
		<LoadPriority>1</LoadPriority>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.287">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="NAudio" Version="2.3.0"/>
		<PackageReference Include="System.Speech" Version="10.0.9"/>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="../EdgeTTS/EdgeTTS.csproj"/>
		<ProjectReference Include="../FetchDependencies/FetchDependencies.csproj"/>
		<ProjectReference Include="../machina/Machina.FFXIV/Machina.FFXIV.csproj"/>
		<ProjectReference Include="../machina/Machina/Machina.csproj"/>
		<ProjectReference Include="../NotACT/NotACT.csproj"/>
		<ProjectReference Include="../OverlayPlugin.Core/OverlayPlugin.Core.csproj"/>
		<ProjectReference Include="../Triggernometry/Source/Triggernometry/TriggernometryPlugin.csproj"/>
		<ProjectReference Include="../PostNamazu/PostNamazu/PostNamazu.csproj"/>
		<ProjectReference Include="../SilverDasher/SilverDasher/SilverDasher.csproj"/>
		<ProjectReference Include="../Unscrambler/Unscrambler/Unscrambler.csproj"/>
		<ProjectReference Include="../PostNamazu/PostNamazu.OverlayHoster/PostNamazu.OverlayHoster.csproj"/>
		<ProjectReference Include="../PostNamazu/PostNamazu.TriggerHoster/PostNamazu.TriggerHoster.csproj"/>
		<!--    <PackageReference Include="Unscrambler.XIV.CN" Version="*" />-->
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Include="../EdgeTTS/voices.json">
			<Link>Resources/voices.json</Link>
			<LogicalName>IINACTEx.Resources.voices.json</LogicalName>
		</EmbeddedResource>
	</ItemGroup>
	<ItemGroup>
		<Reference Include="FFXIV_ACT_Plugin">
			<HintPath>../external_dependencies/FFXIV_ACT_Plugin.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="FFXIV_ACT_Plugin.Common">
			<HintPath>../external_dependencies/SDK/FFXIV_ACT_Plugin.Common.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="FFXIV_ACT_Plugin.Config">
			<HintPath>../external_dependencies/SDK/FFXIV_ACT_Plugin.Config.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="FFXIV_ACT_Plugin.Logfile">
			<HintPath>../external_dependencies/SDK/FFXIV_ACT_Plugin.Logfile.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="FFXIV_ACT_Plugin.Memory">
			<HintPath>../external_dependencies/SDK/FFXIV_ACT_Plugin.Memory.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="FFXIV_ACT_Plugin.Network">
			<HintPath>../external_dependencies/SDK/FFXIV_ACT_Plugin.Network.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="FFXIV_ACT_Plugin.Parse">
			<HintPath>../external_dependencies/SDK/FFXIV_ACT_Plugin.Parse.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="FFXIV_ACT_Plugin.Resource">
			<HintPath>../external_dependencies/SDK/FFXIV_ACT_Plugin.Resource.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="Dalamud.Common">
			<HintPath>$(DalamudLibPath)/Dalamud.Common.dll</HintPath>
			<Private>False</Private>
		</Reference>
	</ItemGroup>
	<ItemGroup>
		<Content Include="../external_dependencies/SafeMemoryReader.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Res/**/*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<TargetPath>$([System.String]::Copy('%(RecursiveDir)').Replace('Res/', ''))%(Filename)%(Extension)</TargetPath>
		</Content>
		<EmbeddedResource Include="logo.png"/>
	</ItemGroup>
	<PropertyGroup Condition="'$(GITHUB_ACTIONS)' == ''">
		<DalamudLibPath>$(appdata)/XIVLauncherCN/addon/Hooks/dev</DalamudLibPath>
		<AssemblySearchPaths>$(AssemblySearchPaths);$(DalamudLibPath)</AssemblySearchPaths>
	</PropertyGroup>
</Project>
