<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Reference Include="Dalamud">
      <HintPath>$(DalamudLibPath)Dalamud.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.24.3" />
    <PackageReference Include="NAudio" Version="2.3.0" />
  </ItemGroup>
</Project>
