<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>
    <ItemGroup>
        <Reference Include="Triggernometry">
            <HintPath>../Triggernometry/Source/Triggernometry/bin/Debug/Triggernometry.dll</HintPath>
        </Reference>
    </ItemGroup>
</Project>
